import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};




import Background from "./Background";

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className="relative min-h-screen">
        <Background /> {/* Ye raha aapka naya animated background */}

        <nav className="fixed top-0 w-full z-50 backdrop-blur-xl bg-black/40 border-b border-white/5 p-4">
          <div className="max-w-6xl mx-auto flex justify-between items-center">
            {/* Brand logo */}
            <div className="flex items-center gap-3">
              <div className="h-9 w-9 rounded-2xl bg-gradient-to-br from-blue-500 via-sky-400 to-indigo-600 shadow-[0_0_24px_rgba(59,130,246,0.6)] flex items-center justify-center">
                <span className="text-sm font-black tracking-[0.25em] text-white">
                  IK
                </span>
              </div>
              <div className="leading-tight">
                <p className="text-[11px] uppercase tracking-[0.28em] text-gray-400">
                  Portfolio
                </p>
                <p className="text-xs md:text-sm font-semibold tracking-tight text-white/90">
                  Iram <span className="text-blue-400">Khalid</span>
                </p>
              </div>
            </div>
            <div className="flex gap-6 text-sm font-medium text-gray-400">
              <a href="#home" className="hover:text-blue-400 transition">Home</a>
              <a href="#about" className="hover:text-blue-400 transition">About</a>
              <a href="#skills" className="hover:text-blue-400 transition">Skills</a>
              <a href="#projects" className="hover:text-blue-400 transition">Projects</a>
              <a href="#contact" className="hover:text-blue-400 transition">Contact</a>
            </div>
          </div>
        </nav>

        <main className="relative z-10">{children}</main>

        <footer className="relative z-10 mt-24 border-t border-white/10 bg-[radial-gradient(circle_at_top,_rgba(37,99,235,0.25),transparent_55%),rgba(3,7,18,0.98)] backdrop-blur-2xl">
          <div className="max-w-6xl mx-auto px-6 py-10 grid grid-cols-1 md:grid-cols-[1.4fr_1fr_1fr] gap-8 text-xs text-gray-400">
            {/* Brand & tagline */}
            <div className="space-y-3">
              <div className="flex items-center gap-3">
                <div className="h-8 w-8 rounded-2xl bg-gradient-to-br from-blue-500 via-sky-400 to-indigo-600 shadow-[0_0_20px_rgba(59,130,246,0.5)] flex items-center justify-center">
                  <span className="text-xs font-black tracking-[0.25em] text-white">
                    IK
                  </span>
                </div>
                <p className="text-sm font-semibold tracking-tight text-white">
                  Iram <span className="text-blue-500">Khalid</span>
                </p>
              </div>
              <p className="text-[11px] text-gray-500">
                Full Stack Developer crafting high‑performance, conversion‑focused
                experiences with Next.js, Shopify and WordPress.
              </p>
              <p className="text-[10px] text-gray-600">
                © {new Date().getFullYear()} All rights reserved.
              </p>
            </div>

            {/* Quick links */}
            <div>
              <p className="text-[11px] font-semibold uppercase tracking-[0.25em] text-gray-500 mb-3">
                Navigate
              </p>
              <div className="flex flex-col gap-1.5 text-[11px]">
                <a href="#home" className="hover:text-blue-400 transition-colors">
                  Home
                </a>
                <a href="#about" className="hover:text-blue-400 transition-colors">
                  About
                </a>
                <a href="#skills" className="hover:text-blue-400 transition-colors">
                  Skills
                </a>
                <a href="#projects" className="hover:text-blue-400 transition-colors">
                  Projects
                </a>
                <a href="#contact" className="hover:text-blue-400 transition-colors">
                  Contact
                </a>
              </div>
            </div>

            {/* Status & back to top */}
            <div className="flex flex-col items-start md:items-end justify-between gap-4">
              <div className="space-y-1 text-[11px] text-gray-500">
                <p className="uppercase tracking-[0.25em] text-gray-500">
                  Availability
                </p>
                <p className="text-gray-300">
                  Open for <span className="text-blue-400">remote</span> projects &
                  collaborations.
                </p>
              </div>
              <a
                href="#home"
                className="inline-flex items-center gap-2 rounded-full border border-white/10 px-4 py-2 text-[11px] uppercase tracking-[0.22em] text-gray-300 hover:border-blue-500/60 hover:text-blue-400 hover:bg-white/5 transition-colors"
              >
                <span className="h-1.5 w-1.5 rounded-full bg-blue-500 animate-pulse" />
                Back to top
              </a>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}